version: '3'
services:
  plex:
    container_name: Plex
    image: plexinc/pms-docker # You may need to build it locally first: github.com/plexinc/pms-docker.git
    ports:
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
        #- 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    environment:
      - TZ=Europe/Berlin
      - PLEX_CLAIM=claim-XXXXXXX
      - ADVERTISE_IP=http:XXX.XXX.XXX.XXX:32400/
    hostname: NASberry
    volumes:
      - <path>/config/plex:/config
      - <path>/media/Series:/tv
      - <path>/media/Films:/movies
      - <path>/media/Musique:/music
      - <path>/media/Videos/Lives:/lives
      - /tmp:/transcode
    restart: unless-stopped
