version: "3"
services:
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "8081:80/tcp"
      - "443:443/tcp"
    environment:
      TZ: 'Europe/Paris'
      WEBPASSWORD: # password
      ServerIP: '192.168.1.52'
    volumes:
       - '<path>/config/PiHole/etc-pihole/:/etc/pihole/'
       - '<path>/config/PiHole/etc-dnsmasq.d/:/etc/dnsmasq.d/'
    dns:
      - 127.0.0.1
      - 1.1.1.1
    cap_add:
      - NET_ADMIN
    restart: always
