version: "3"
services:
  transmission:
    image: linuxserver/transmission
    container_name: transmission
    environment:
      - PUID=998
      - PGID=100
      - TZ=Europe/Paris
      - USER=admin #optional
      - PASS= #optional password
    volumes:
      - <path>/config/Transmission:/config
      - <path>/incoming:/downloads
      - <path>/incoming/watch:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
