version: '3'

services:
    core:
        image: florentdufour/bitcoin:0.20.1
        container_name: bitcoin
        hostname: bitcoin
        volumes:
        - <path>/bitcoin:/root/.bitcoin
        stdin_open: true # -i
        tty: true # -t
        restart: always
